version: "3.9"

services:
  web:
    image: resume-app:v2
    ports:
      - "8080:80"
    volumes:
      - ./site:/usr/share/nginx/html
    environment:
      - APP_ENV=production
      - OWNER=Temi
